#include "bluenrg_lp_evb_io.h"
#include "rf_driver_ll_pwr.h"

void BSP_IO_Init(void)
{
	LL_PWR_EnablePDA(LL_PWR_PUPD_IO0);
	LL_PWR_EnablePDA(LL_PWR_PUPD_IO1);
	LL_PWR_EnablePDA(LL_PWR_PUPD_IO2);
	LL_PWR_EnablePDA(LL_PWR_PUPD_IO3);
	LL_PWR_EnablePDA(LL_PWR_PUPD_IO4);
	LL_PWR_EnablePDA(LL_PWR_PUPD_IO5);
	LL_PWR_EnablePUA(LL_PWR_PUPD_IO6);
	LL_PWR_EnablePDA(LL_PWR_PUPD_IO7);
	LL_PWR_EnablePDA(LL_PWR_PUPD_IO8);
	LL_PWR_EnablePUA(LL_PWR_PUPD_IO9);
	LL_PWR_EnablePDA(LL_PWR_PUPD_IO10);
	LL_PWR_EnablePDA(LL_PWR_PUPD_IO11); 
	LL_PWR_EnablePDA(LL_PWR_PUPD_IO12);
	LL_PWR_EnablePDA(LL_PWR_PUPD_IO13); 
	LL_PWR_EnablePDA(LL_PWR_PUPD_IO14);
	LL_PWR_EnablePDA(LL_PWR_PUPD_IO15);

	LL_PWR_EnablePDB(LL_PWR_PUPD_IO0);
	LL_PWR_EnablePDB(LL_PWR_PUPD_IO1);
	LL_PWR_EnablePDB(LL_PWR_PUPD_IO2);
	LL_PWR_EnablePDB(LL_PWR_PUPD_IO3);
	LL_PWR_EnablePDB(LL_PWR_PUPD_IO4);
	LL_PWR_EnablePDB(LL_PWR_PUPD_IO5);
	LL_PWR_EnablePDB(LL_PWR_PUPD_IO6);
	LL_PWR_EnablePDB(LL_PWR_PUPD_IO7);
	LL_PWR_EnablePUB(LL_PWR_PUPD_IO8);
	LL_PWR_EnablePUB(LL_PWR_PUPD_IO9);
	LL_PWR_EnablePDB(LL_PWR_PUPD_IO10);
	LL_PWR_EnablePDB(LL_PWR_PUPD_IO11);
	LL_PWR_EnablePDB(LL_PWR_PUPD_IO14);
	LL_PWR_EnablePDB(LL_PWR_PUPD_IO15);
}



